# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='brand',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='antiLockBrakes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='engineSize',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='mileage',
            field=models.IntegerField(default=20222),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(default='bwwq', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price',
            field=models.IntegerField(default=2011222),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='report',
            field=models.CharField(default='asdf', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='typeOfBike',
            field=models.CharField(default='asdfasdfasf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='year',
            field=models.IntegerField(default=2011),
        ),
    ]
