# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20170812_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Green', 'Green')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='mileage',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price',
            field=models.IntegerField(default=20000),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='typeOfBike',
            field=models.CharField(choices=[('Cruiser', 'Cruiser'), ('Supersport', 'Supersport'), ('Standard', 'Standard')], default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
