# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20170812_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='pics',
            field=models.FileField(upload_to='marketplace/static/marketplace/pics'),
        ),
    ]
