# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20170812_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='pic_1',
            field=models.FileField(default='marketplace/static/marketplace/pics/default.png', upload_to='marketplace/static/marketplace/pics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='pic_2',
            field=models.FileField(default='marketplace/static/marketplace/pics/default.png', upload_to='marketplace/static/marketplace/pics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='pic_3',
            field=models.FileField(default='marketplace/static/marketplace/pics/default.png', upload_to='marketplace/static/marketplace/pics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='pic_4',
            field=models.FileField(default='marketplace/static/marketplace/pics/default.png', upload_to='marketplace/static/marketplace/pics/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='pic_5',
            field=models.FileField(default='marketplace/static/marketplace/pics/default.png', upload_to='marketplace/static/marketplace/pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='pics',
            field=models.FileField(upload_to='marketplace/static/marketplace/pics/'),
        ),
    ]
